// src/constants/theme.ts
export const theme = {
  colors: {
    cream:       '#FBF4EC',
    ink:         '#3D2317',
    soft:        '#7A6557',
    muted:       '#EFE3D7',
    border:      '#E7D4C3',
    card:        '#FFFDFC',
    accent:      '#C97E58',
    accentLight: '#F4DDCF',
    accentMid:   '#D79A73',
    warn:        '#E07A5F',
    warnLight:   '#FAE8E3',
    green:       '#52B788',
    greenLight:  '#D8F0E5',
    yellow:      '#F4A261',
    yellowLight: '#FEF3CD',
    red:         '#E07A5F',
    redLight:    '#FAE8E3',
  },
  fonts: {
    sans:    'System',
    display: 'Georgia',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm:   8,
    md:   12,
    lg:   16,
    xl:   20,
    full: 100,
  },
}